### ISSUE TITLE
Missing plone 5 profile for geo extra

### ISSUE THREAD

**Issue by Nachtalb** [4teamwork/ftw.addressblock#26]
The profile `ftw/addressblock/geo/profiles/default` contains a `jsregistry.xml` file, which should be ported to plone 5's `registry.xml`. 

The `authenticated` attribute can be achieved by using an expression like this in the bundle: 
```xml
<value key="expression">python: member is not None</value>
```

Attention here because only one of the 2 defined javascript is for authenticated users only not both.

**Comment by maethu** [comment]
No longer necessary due https://github.com/4teamwork/ftw.simplelayout/pull/564
