### ISSUE TITLE
Edit overlay closes on enter (map location search).

### ISSUE THREAD

**Issue by busykoala** [4teamwork/ftw.addressblock#31]
In the overlay on enter the location entered is used correctly, but the overlay will be closed instead of the expected search results underneath the entry. This happens only when adding the block. After that the search results are shown correctly.

![image](https://user-images.githubusercontent.com/29920936/68935671-3b081e80-0799-11ea-9666-fe8525da4a7e.png)

**Comment by maethu** [comment]
Fixed with 
- https://github.com/4teamwork/ftw.simplelayout/pull/564
- https://github.com/4teamwork/ftw.addressblock/pull/32

**Comment by busykoala** [comment]
This seems to be working now.
